before:
  hooks:
    - go mod download
    - go generate ./...

builds:
  - id: default
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - arm
      - arm64
      - amd64
      - 386
    ldflags:
      - -X github.com/superfly/flyctl/internal/buildinfo.environment=production
      - -X github.com/superfly/flyctl/internal/buildinfo.buildDate={{ .Date }}
      - -X github.com/superfly/flyctl/internal/buildinfo.version={{ .Version }}
      - -X github.com/superfly/flyctl/internal/buildinfo.commit={{ .ShortCommit }}
 
release:
  github:
    owner: ThatMG393
    name: flyctl
