name: Auto-Build
on:
  push:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  releases-matrix:
    name: Build & Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"
          check-latest: true

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --config .goreleaser.dev.yml --clean
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
