name: Auto-Build
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: action/checkout@master
      
      - name: Install Go
        run: sudo apt update && sudo apt install golang -y
      
      - name: Build
        run: CGO_ENABLED="1" GOOS=linux GOARCH=arm go build

      - name: Upload built binary
        uses: actions/upload-artifact@master
        with:
          name: flyctl-debug
          path: bin/*
